### ISSUE TITLE
Change Kortforsyningsplugin to deprecated in QGIS plugin repository

### ISSUE THREAD

**Issue by MieWinstrup** [Kortforsyningen/Qgis_plugin_Kortforsyningen_v3#26]
Da det nu er Dataforsyningspluginet, der bruges, så kunne det være en idé i QGIS' plugin repository at angive at Kortforsyningspluginet er 'deprecated' - dvs. forældet.

Det gør I således:

1. Log in med jeres bruger på https://plugins.qgis.org/accounts/login/
2. Søg efter Kortforsyningspluginet oppe i øverste højre søgefelt
3. Klik på 'Edit' - her vist for Datafordeler-pluginet
![image](https://github.com/SDFIdk/Qgis_plugin_Kortforsyningen_v3/assets/16276034/a57db677-8798-44d5-9a30-8fd22269e148)
4. Sæt hak ved 'Deprecated' - her vist for Datafordeler-pluginet.
![image](https://github.com/SDFIdk/Qgis_plugin_Kortforsyningen_v3/assets/16276034/f98a9a9d-ae6f-4485-bba0-5db76c4ef49b)
I kan også skrive en kort forklarende tekst under 'About'

**Comment by DocDemar** [comment]
Jeg kan ikke finde Kortforsyningen plugin i Qgis plugin repo
det findes heller ikke under 'Mine plugins'
Har du mulighed for at sende et link?

**Comment by MieWinstrup** [comment]
Du har ret. Pluginet er ikke i QGIS plugin repository, så luk blot dette issue.

**Comment by DocDemar** [comment]
tjek - så tror jeg at det er på tide at arkiverer dette repo
