### ISSUE TITLE
Fejl ved installation af Kortforsyningsplugin til QGis 3.0 i Windows10 64 bit

### ISSUE THREAD

**Issue by Simun** [Kortforsyningen/Qgis_plugin_Kortforsyningen_v3#6]
![fejl](https://user-images.githubusercontent.com/603768/36734973-f6e7331c-1bcc-11e8-975b-d7dd3375f9be.png)

**Comment by MieWinstrup** [comment]
@Simun - Hvilken version af Kortforsyningspluginet prøver du at hente - version 2.0 eller 2.1?

**Comment by Simun** [comment]
Den påstår at være version 2.1
