### ISSUE TITLE
Fortsat en fej i version 2.2 i QGis3.0 i Windows10 64 bit

### ISSUE THREAD

**Issue by Simun** [Kortforsyningen/Qgis_plugin_Kortforsyningen_v3#8]
Jeg får en fejl når jeg installerer version 2.2 af Kortforsyningens plugn
![fejl1](https://user-images.githubusercontent.com/603768/37291842-759a3206-2607-11e8-85bc-eb742f63eb98.png)

**Comment by MieWinstrup** [comment]
@Simun - hvordan går det når du installerer version 2.3?

**Comment by Simun** [comment]
Jeg fik som sagt en advarsel da jeg installerede, men den kører som en drøm.

**Comment by Simun** [comment]
Glem den sidste meddelelse. Jeg havde ikke set at der er en ny version. Jeg afprøver den senere.

**Comment by Simun** [comment]
Jeg har opgraderet til version 2.3 uden problemer både på arbejde og hjemme.
Lækker plugin.
